;;; -*- TI-Asm -*-

 include "mem.asm"
 include "nodes.asm"
 include "types.asm"
 include "list.asm"
 include "objects.asm"
 include "word.asm"
 include "float.asm"
 include "parse.asm"
 include "stack.asm"
 include "proc.asm"
 include "eval.asm"
 include "primitives.asm"
 include "assert.asm"
 include "data.asm"
