;;; -*- TI-Asm -*-

 include "mem.asm"
 include "nodes.asm"
 include "gc.asm"
 include "types.asm"
 include "list.asm"
 include "objects.asm"
 include "word.asm"
 include "float.asm"
 include "parse.asm"
 include "stack.asm"
 include "proc.asm"
 include "eval.asm"
 include "p-cntrl.asm"
 include "p-data.asm"
 include "p-logic.asm"
 include "p-math.asm"
 include "p-worksp.asm"

 include "assert.asm"
 include "data.asm"
